VERSION="2.2.1"
NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[
  "GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD",
]

[DOCUMENTATION]
ORG_NAME="LibreXLM"
ORG_DESCRIPTION="An Autonomous experimental Trading Token on the Stellar Network"
ORG_DBA="https://librequidity.org"
ORG_URL="https://librequidity.org"
ORG_LOGO="https://librequidity.org/img/LIBRE_PNG.jpg"
ORG_OFFICIAL_EMAIL="librexlm@gmail.com"

[[PRINCIPALS]]
name="LIBRE"
email="librexlm@gmail.com"
github="LibreXLM"

[[CURRENCIES]]
code="ReverseLibre"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="ReverseLibre"
desc="This token is part of the LibreTradingEcosystem, a network of interconnected assets that continuously trade against one another in AMM liquidity pools. The design goal is to study how coordinated pools, cross-pairs, and rebalancing can compound fees over time and translate pure trading activity into emergent value."
conditions="This is a personal, experimental trading-system token for research and education. Crypto assets are highly volatile and you may lose your entire stake. There is no redemption right, no price peg, and no guarantees. The token does not represent equity, debt, custody, claims, dividends, or ownership, and confers no rights or expectations of profit from the issuerâ€™s efforts. Supply and parameters may change without notice."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=false
anchor_asset="ReverseLibre"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="LibreVolume"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="LibreVolume"
desc="This token is part of the LibreTradingEcosystem, a network of interconnected assets..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="LibreVolume"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yZOMB"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yZOMB"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yZOMB"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yFRED"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yFRED"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yFRED"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yLMT"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yLMT"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yLMT"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yLUMOS"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yLUMOS"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yLUMOS"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="maxBREAD"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="maxBREAD"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="maxBREAD"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="200XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="200XLM"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="200XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yDWARF"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yDWARF"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yDWARF"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="100XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="100XLM"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="100XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="not100XLM"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="not100XLM"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="not100XLM"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yTATT"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yTATT"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yTATT"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yBBOI"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yBBOI"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yBBOI"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="yGRACE"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="yGRACE"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="yGRACE"
anchor_asset_type="crypto"

[[CURRENCIES]]
code="Libre420"
status="live"
issuer="GBVYKIM4QGW7NK3Q5S76GWMZMLAWYB6FB43JQ4J7ZOXHAA3LEZZGYHSD"
display_decimals=7
name="Libre420"
desc="This token is part of the LibreTradingEcosystem..."
conditions="This is a personal, experimental trading-system token..."
image="https://librequidity.org/LIBRE_PNG.jpg"
is_asset_anchored=false
is_unlimited=true
anchor_asset="Libre420"
anchor_asset_type="crypto"
